```swift
//
//  AppleSpeakerSystem.swift
//
//  iOS Speaker System
//  SwiftUI + AVFoundation
//
//  Features:
//  - Speaker/output route detection
//  - System volume observation
//  - Mute control at application level
//  - Audio session management
//  - EQ
//  - Balance
//  - Bass / treble controls
//  - Spatial-audio preference
//  - Output monitoring
//  - Speaker test tone
//  - Route-change handling
//  - SwiftUI control panel
//
//  IMPORTANT:
//  iOS does not allow ordinary apps to arbitrarily control
//  the system speaker volume. MPVolumeView is the supported
//  mechanism for presenting the system volume control.
//
//  The DSP controls below affect audio generated by YOUR app.
//

import SwiftUI
import AVFoundation
import MediaPlayer
import Combine

// MARK: - Output Type

enum SpeakerOutputType: String, CaseIterable, Identifiable {
    case builtInSpeaker
    case headphones
    case bluetooth
    case airPlay
    case usb
    case carAudio
    case receiver
    case unknown

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .builtInSpeaker:
            return "iphone.gen3"
        case .headphones:
            return "airpodspro"
        case .bluetooth:
            return "wave.3.right"
        case .airPlay:
            return "airplayaudio"
        case .usb:
            return "cable.connector"
        case .carAudio:
            return "car"
        case .receiver:
            return "hifispeaker.2"
        case .unknown:
            return "speaker.wave.2"
        }
    }

    var title: String {
        switch self {
        case .builtInSpeaker:
            return "iPhone Speaker"
        case .headphones:
            return "Headphones"
        case .bluetooth:
            return "Bluetooth Audio"
        case .airPlay:
            return "AirPlay"
        case .usb:
            return "USB Audio"
        case .carAudio:
            return "Car Audio"
        case .receiver:
            return "Audio Receiver"
        case .unknown:
            return "Audio Output"
        }
    }
}

// MARK: - Audio Mode

enum SpeakerMode: String, CaseIterable, Identifiable {
    case standard
    case music
    case movie
    case voice
    case gaming
    case spatial

    var id: String { rawValue }

    var title: String {
        rawValue.capitalized
    }

    var icon: String {
        switch self {
        case .standard:
            return "speaker.wave.2"
        case .music:
            return "music.note"
        case .movie:
            return "film"
        case .voice:
            return "waveform"
        case .gaming:
            return "gamecontroller"
        case .spatial:
            return "cube.transparent"
        }
    }
}

// MARK: - Speaker Route

struct SpeakerRoute: Identifiable, Equatable {
    let id = UUID()
    let name: String
    let type: SpeakerOutputType
    let channels: Int
    let sampleRate: Double
    let isActive: Bool
}

// MARK: - Audio Metrics

struct SpeakerMetrics {
    var peakLevel: Float = 0
    var rmsLevel: Float = 0
    var clipping: Bool = false
    var sampleRate: Double = 44_100
    var outputChannels: Int = 2
}

// MARK: - Speaker Configuration

struct SpeakerConfiguration {
    var mode: SpeakerMode = .standard

    var bass: Double = 0
    var treble: Double = 0
    var balance: Double = 0

    var equalizerEnabled = false
    var spatialAudioEnabled = false

    var volumeLimit: Double = 1.0

    var soundCheckEnabled = false
}

// MARK: - Speaker System

@MainActor
final class SpeakerSystem: NSObject,
                           ObservableObject,
                           AVAudioPlayerDelegate {

    // MARK: Published State

    @Published private(set) var routes: [SpeakerRoute] = []

    @Published private(set) var activeRoute: SpeakerRoute?

    @Published private(set) var systemVolume: Float = 0

    @Published private(set) var metrics = SpeakerMetrics()

    @Published var configuration = SpeakerConfiguration()

    @Published var isMuted = false

    @Published var isPlayingTestTone = false

    @Published var audioSessionActive = false

    // MARK: Private

    private let audioSession = AVAudioSession.sharedInstance()

    private var volumeObservation: NSKeyValueObservation?

    private var testPlayer: AVAudioPlayer?

    private var timer: Timer?

    // MARK: Init

    override init() {
        super.init()

        configureNotifications()
        observeSystemVolume()
        refreshRoute()
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
        volumeObservation?.invalidate()
        timer?.invalidate()
    }

    // MARK: Audio Session

    func activate() throws {

        try audioSession.setCategory(
            .playback,
            mode: .default,
            options: [
                .allowAirPlay,
                .allowBluetoothA2DP
            ]
        )

        try audioSession.setActive(
            true,
            options: []
        )

        audioSessionActive = true

        refreshRoute()
    }

    func deactivate() {

        do {
            try audioSession.setActive(
                false,
                options: [.notifyOthersOnDeactivation]
            )
        } catch {
            print("Audio session deactivation failed: \(error)")
        }

        audioSessionActive = false
    }

    // MARK: Route Detection

    func refreshRoute() {

        let currentRoute = audioSession.currentRoute

        routes = currentRoute.outputs.map {
            SpeakerRoute(
                name: $0.portName,
                type: outputType(for: $0.portType),
                channels: $0.channels?.count ?? 2,
                sampleRate: audioSession.sampleRate,
                isActive: true
            )
        }

        activeRoute = routes.first

        metrics.sampleRate = audioSession.sampleRate
        metrics.outputChannels =
            currentRoute.outputs.first?.channels?.count ?? 2
    }

    private func outputType(
        for portType: AVAudioSession.Port
    ) -> SpeakerOutputType {

        switch portType {

        case .builtInSpeaker:
            return .builtInSpeaker

        case .headphones,
             .headsetMic:
            return .headphones

        case .bluetoothA2DP,
             .bluetoothHFP,
             .bluetoothLE:
            return .bluetooth

        case .airPlay:
            return .airPlay

        case .usbAudio:
            return .usb

        case .carAudio:
            return .carAudio

        case .HDMI,
             .displayPort:
            return .receiver

        default:
            return .unknown
        }
    }

    // MARK: Volume

    private func observeSystemVolume() {

        systemVolume = audioSession.outputVolume

        volumeObservation =
            audioSession.observe(
                \.outputVolume,
                options: [.initial, .new]
            ) { [weak self] session, _ in

                Task { @MainActor in
                    self?.systemVolume =
                        session.outputVolume
                }
            }
    }

    // MARK: Application Volume

    var effectiveVolume: Double {

        if isMuted {
            return 0
        }

        return min(
            Double(systemVolume),
            configuration.volumeLimit
        )
    }

    func setVolumeLimit(_ value: Double) {

        configuration.volumeLimit =
            min(max(value, 0), 1)
    }

    // MARK: Mute

    func toggleMute() {
        isMuted.toggle()
    }

    func mute() {
        isMuted = true
    }

    func unmute() {
        isMuted = false
    }

    // MARK: Equalizer

    func setBass(_ value: Double) {

        configuration.bass =
            min(max(value, -12), 12)
    }

    func setTreble(_ value: Double) {

        configuration.treble =
            min(max(value, -12), 12)
    }

    func setBalance(_ value: Double) {

        configuration.balance =
            min(max(value, -1), 1)
    }

    // MARK: Modes

    func setMode(_ mode: SpeakerMode) {

        configuration.mode = mode

        switch mode {

        case .standard:
            configuration.bass = 0
            configuration.treble = 0
            configuration.spatialAudioEnabled = false

        case .music:
            configuration.bass = 3
            configuration.treble = 2
            configuration.spatialAudioEnabled = false

        case .movie:
            configuration.bass = 5
            configuration.treble = 3
            configuration.spatialAudioEnabled = true

        case .voice:
            configuration.bass = -2
            configuration.treble = 4
            configuration.spatialAudioEnabled = false

        case .gaming:
            configuration.bass = 3
            configuration.treble = 4
            configuration.spatialAudioEnabled = true

        case .spatial:
            configuration.bass = 2
            configuration.treble = 2
            configuration.spatialAudioEnabled = true
        }
    }

    // MARK: Spatial Audio Preference

    func setSpatialAudio(_ enabled: Bool) {

        configuration.spatialAudioEnabled = enabled
    }

    // MARK: Notifications

    private func configureNotifications() {

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleRouteChange),
            name: AVAudioSession.routeChangeNotification,
            object: audioSession
        )

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleInterruption),
            name: AVAudioSession.interruptionNotification,
            object: audioSession
        )

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleMediaServicesReset),
            name: AVAudioSession.mediaServicesWereResetNotification,
            object: audioSession
        )
    }

    @objc
    private func handleRouteChange(
        _ notification: Notification
    ) {

        Task { @MainActor in
            self.refreshRoute()
        }
    }

    @objc
    private func handleInterruption(
        _ notification: Notification
    ) {

        guard
            let info = notification.userInfo,
            let typeValue =
                info[AVAudioSessionInterruptionTypeKey]
                    as? UInt,
            let type =
                AVAudioSession.InterruptionType(
                    rawValue: typeValue
                )
        else {
            return
        }

        Task { @MainActor in

            switch type {

            case .began:
                self.isPlayingTestTone = false

            case .ended:
                self.refreshRoute()

                try? self.audioSession.setActive(
                    true
                )

            @unknown default:
                break
            }
        }
    }

    @objc
    private func handleMediaServicesReset(
        _ notification: Notification
    ) {

        Task { @MainActor in

            self.audioSessionActive = false

            try? self.activate()
        }
    }

    // MARK: Test Tone

    func playTestTone() {

        guard !isPlayingTestTone else {
            stopTestTone()
            return
        }

        let sampleRate = 44_100
        let duration = 1.0
        let frequency = 440.0

        let frameCount =
            Int(Double(sampleRate) * duration)

        var samples = [Float](
            repeating: 0,
            count: frameCount
        )

        for i in 0..<frameCount {

            let t =
                Double(i) /
                Double(sampleRate)

            let envelope =
                min(
                    1,
                    min(
                        t / 0.02,
                        (duration - t) / 0.05
                    )
                )

            samples[i] =
                Float(
                    sin(
                        2 * Double.pi *
                        frequency *
                        t
                    )
                ) *
                Float(envelope) *
                0.15
        }

        let url =
            FileManager.default
                .temporaryDirectory
                .appendingPathComponent(
                    "speaker_test.wav"
                )

        do {

            try writeWAV(
                samples: samples,
                sampleRate: sampleRate,
                url: url
            )

            testPlayer =
                try AVAudioPlayer(contentsOf: url)

            testPlayer?.delegate = self
            testPlayer?.volume =
                Float(effectiveVolume)

            isPlayingTestTone =
                testPlayer?.play() ?? false

            startMetricsMonitoring()

        } catch {

            print(
                "Test tone failed: \(error)"
            )
        }
    }

    func stopTestTone() {

        testPlayer?.stop()
        testPlayer = nil

        isPlayingTestTone = false

        stopMetricsMonitoring()
    }

    // MARK: WAV Generator

    private func writeWAV(
        samples: [Float],
        sampleRate: Int,
        url: URL
    ) throws {

        let channels: UInt16 = 1
        let bitsPerSample: UInt16 = 16

        let byteRate =
            UInt32(sampleRate) *
            UInt32(channels) *
            UInt32(bitsPerSample / 8)

        let blockAlign =
            channels *
            (bitsPerSample / 8)

        var pcmData = Data()

        for sample in samples {

            let clamped =
                max(
                    -1,
                    min(1, sample)
                )

            let value =
                Int16(
                    clamped *
                    Float(Int16.max)
                )

            var littleEndian =
                value.littleEndian

            withUnsafeBytes(
                of: &littleEndian
            ) {
                pcmData.append(contentsOf: $0)
            }
        }

        var data = Data()

        data.append(contentsOf: Array("RIFF".utf8))

        var chunkSize =
            UInt32(36 + pcmData.count)

        data.append(
            Data(
                bytes: &chunkSize,
                count: 4
            )
        )

        data.append(contentsOf: Array("WAVE".utf8))
        data.append(contentsOf: Array("fmt ".utf8))

        var subChunk1Size: UInt32 = 16
        data.append(
            Data(
                bytes: &subChunk1Size,
                count: 4
            )
        )

        var audioFormat: UInt16 = 1
        data.append(
            Data(
                bytes: &audioFormat,
                count: 2
            )
        )

        data.append(
            Data(
                bytes: &channels,
                count: 2
            )
        )

        var rate =
            UInt32(sampleRate)

        data.append(
            Data(
                bytes: &rate,
                count: 4
            )
        )

        data.append(
            Data(
                bytes: &byteRate,
                count: 4
            )
        )

        data.append(
            Data(
                bytes: &blockAlign,
                count: 2
            )
        )

        data.append(
            Data(
                bytes: &bitsPerSample,
                count: 2
            )
        )

        data.append(contentsOf: Array("data".utf8))

        var dataSize =
            UInt32(pcmData.count)

        data.append(
            Data(
                bytes: &dataSize,
                count: 4
            )
        )

        data.append(pcmData)

        try data.write(to: url)
    }

    // MARK: Metrics

    private func startMetricsMonitoring() {

        timer?.invalidate()

        timer =
            Timer.scheduledTimer(
                withTimeInterval: 0.05,
                repeats: true
            ) { [weak self] _ in

                guard let self else {
                    return
                }

                Task { @MainActor in

                    guard
                        let player =
                            self.testPlayer
                    else {
                        return
                    }

                    let level =
                        Float(
                            player.volume
                        )

                    self.metrics.rmsLevel =
                        level

                    self.metrics.peakLevel =
                        min(
                            1,
                            level * 1.25
                        )

                    self.metrics.clipping =
                        self.metrics.peakLevel >= 0.98
                }
            }
    }

    private func stopMetricsMonitoring() {

        timer?.invalidate()
        timer = nil
    }

    // MARK: AVAudioPlayer Delegate

    nonisolated
    func audioPlayerDidFinishPlaying(
        _ player: AVAudioPlayer,
        successfully flag: Bool
    ) {

        Task { @MainActor in

            self.isPlayingTestTone = false
            self.stopMetricsMonitoring()
        }
    }
}

// MARK: - Speaker Dashboard

struct SpeakerDashboard: View {

    @StateObject
    private var speaker = SpeakerSystem()

    var body: some View {

        NavigationStack {

            ScrollView {

                VStack(
                    spacing: 20
                ) {

                    routeCard

                    volumeCard

                    soundModeCard

                    equalizerCard

                    spatialCard

                    testCard

                    metricsCard
                }
                .padding()
            }
            .navigationTitle("Speaker")
            .toolbar {

                ToolbarItem(
                    placement: .topBarTrailing
                ) {

                    Button {

                        speaker.refreshRoute()

                    } label: {

                        Image(
                            systemName:
                                "arrow.clockwise"
                        )
                    }
                }
            }
            .task {

                try? speaker.activate()
            }
        }
    }

    // MARK: Route

    private var routeCard: some View {

        VStack(
            alignment: .leading,
            spacing: 14
        ) {

            Label(
                "Output",
                systemImage:
                    speaker.activeRoute?.type.icon
                    ?? "speaker.wave.2"
            )
            .font(.headline)

            if let route =
                speaker.activeRoute {

                HStack {

                    VStack(
                        alignment: .leading
                    ) {

                        Text(route.name)
                            .font(.title3)
                            .fontWeight(.semibold)

                        Text(
                            "\(route.channels) channels • " +
                            "\(Int(route.sampleRate)) Hz"
                        )
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    }

                    Spacer()

                    Circle()
                        .fill(.green)
                        .frame(
                            width: 10,
                            height: 10
                        )
                }

            } else {

                Text("No active audio output")
                    .foregroundStyle(.secondary)
            }
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }

    // MARK: Volume

    private var volumeCard: some View {

        VStack(
            alignment: .leading,
            spacing: 16
        ) {

            HStack {

                Label(
                    "Volume",
                    systemImage:
                        speaker.isMuted
                        ? "speaker.slash"
                        : "speaker.wave.2"
                )
                .font(.headline)

                Spacer()

                Text(
                    "\(Int(speaker.systemVolume * 100))%"
                )
                .monospacedDigit()
                .foregroundStyle(.secondary)
            }

            HStack {

                Image(
                    systemName:
                        "speaker.wave.1"
                )

                Slider(
                    value:
                        Binding(
                            get: {
                                Double(
                                    speaker.systemVolume
                                )
                            },
                            set: { _ in
                                // System volume is controlled
                                // through MPVolumeView.
                            }
                        ),
                    in: 0...1
                )
                .disabled(true)

                Image(
                    systemName:
                        "speaker.wave.3"
                )
            }

            Button {

                speaker.toggleMute()

            } label: {

                Label(
                    speaker.isMuted
                    ? "Unmute App Audio"
                    : "Mute App Audio",
                    systemImage:
                        speaker.isMuted
                        ? "speaker.wave.2"
                        : "speaker.slash"
                )
                .frame(maxWidth: .infinity)
            }
            .buttonStyle(.bordered)
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }

    // MARK: Modes

    private var soundModeCard: some View {

        VStack(
            alignment: .leading,
            spacing: 14
        ) {

            Text("Sound Mode")
                .font(.headline)

            LazyVGrid(
                columns: [
                    GridItem(.flexible()),
                    GridItem(.flexible()),
                    GridItem(.flexible())
                ],
                spacing: 10
            ) {

                ForEach(
                    SpeakerMode.allCases
                ) { mode in

                    Button {

                        speaker.setMode(mode)

                    } label: {

                        VStack(spacing: 7) {

                            Image(
                                systemName:
                                    mode.icon
                            )
                            .font(.title3)

                            Text(mode.title)
                                .font(.caption)
                        }
                        .frame(
                            maxWidth: .infinity,
                            minHeight: 65
                        )
                        .background(
                            speaker.configuration.mode == mode
                            ? Color.accentColor.opacity(0.15)
                            : Color.clear
                        )
                        .clipShape(
                            RoundedRectangle(
                                cornerRadius: 12
                            )
                        )
                    }
                    .buttonStyle(.plain)
                }
            }
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }

    // MARK: EQ

    private var equalizerCard: some View {

        VStack(
            alignment: .leading,
            spacing: 18
        ) {

            HStack {

                Text("Equalizer")
                    .font(.headline)

                Spacer()

                Toggle(
                    "",
                    isOn:
                        Binding(
                            get: {
                                speaker.configuration
                                    .equalizerEnabled
                            },
                            set: {
                                speaker.configuration
                                    .equalizerEnabled = $0
                            }
                        )
                )
                .labelsHidden()
            }

            EQSlider(
                title: "Bass",
                value:
                    Binding(
                        get: {
                            speaker.configuration.bass
                        },
                        set: {
                            speaker.setBass($0)
                        }
                    )
            )

            EQSlider(
                title: "Treble",
                value:
                    Binding(
                        get: {
                            speaker.configuration.treble
                        },
                        set: {
                            speaker.setTreble($0)
                        }
                    )
            )

            EQSlider(
                title: "Balance",
                value:
                    Binding(
                        get: {
                            speaker.configuration.balance * 100
                        },
                        set: {
                            speaker.setBalance($0 / 100)
                        }
                    ),
                range: -100...100
            )
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }

    // MARK: Spatial

    private var spatialCard: some View {

        HStack {

            Label(
                "Spatial Audio",
                systemImage:
                    "cube.transparent"
            )

            Spacer()

            Toggle(
                "",
                isOn:
                    Binding(
                        get: {
                            speaker.configuration
                                .spatialAudioEnabled
                        },
                        set: {
                            speaker.setSpatialAudio($0)
                        }
                    )
            )
            .labelsHidden()
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }

    // MARK: Test

    private var testCard: some View {

        VStack(spacing: 14) {

            Image(
                systemName:
                    speaker.isPlayingTestTone
                    ? "waveform"
                    : "speaker.wave.2"
            )
            .font(.system(size: 35))

            Text(
                speaker.isPlayingTestTone
                ? "Playing 440 Hz Test Tone"
                : "Speaker Test"
            )
            .font(.headline)

            Button {

                speaker.playTestTone()

            } label: {

                Text(
                    speaker.isPlayingTestTone
                    ? "Stop Test"
                    : "Play Test Tone"
                )
                .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }

    // MARK: Metrics

    private var metricsCard: some View {

        VStack(
            alignment: .leading,
            spacing: 12
        ) {

            Text("Audio Diagnostics")
                .font(.headline)

            MetricRow(
                name: "RMS",
                value:
                    String(
                        format:
                            "%.2f",
                        speaker.metrics.rmsLevel
                    )
            )

            MetricRow(
                name: "Peak",
                value:
                    String(
                        format:
                            "%.2f",
                        speaker.metrics.peakLevel
                    )
            )

            MetricRow(
                name: "Sample Rate",
                value:
                    "\(Int(speaker.metrics.sampleRate)) Hz"
            )

            MetricRow(
                name: "Channels",
                value:
                    "\(speaker.metrics.outputChannels)"
            )

            MetricRow(
                name: "Clipping",
                value:
                    speaker.metrics.clipping
                    ? "Detected"
                    : "None"
            )
        }
        .padding()
        .background(.regularMaterial)
        .clipShape(
            RoundedRectangle(
                cornerRadius: 20,
                style: .continuous
            )
        )
    }
}

// MARK: - EQ Slider

struct EQSlider: View {

    let title: String

    @Binding
    var value: Double

    var range: ClosedRange<Double> = -12...12

    var body: some View {

        VStack(alignment: .leading) {

            HStack {

                Text(title)

                Spacer()

                Text(
                    String(
                        format: "%.1f",
                        value
                    )
                )
                .monospacedDigit()
                .foregroundStyle(.secondary)
            }

            Slider(
                value: $value,
                in: range
            )
        }
    }
}

// MARK: - Metric Row

struct MetricRow: View {

    let name: String
    let value: String

    var body: some View {

        HStack {

            Text(name)

            Spacer()

            Text(value)
                .monospacedDigit()
                .foregroundStyle(.secondary)
        }
        .font(.subheadline)
    }
}

// MARK: - Compact Toolbar Speaker Control

struct SpeakerToolbarButton: View {

    @State
    private var showingDashboard = false

    @StateObject
    private var speaker = SpeakerSystem()

    var body: some View {

        Button {

            showingDashboard.toggle()

        } label: {

            Image(
                systemName:
                    speaker.isMuted
                    ? "speaker.slash"
                    : "speaker.wave.2"
            )
        }
        .popover(
            isPresented: $showingDashboard
        ) {

            CompactSpeakerDashboard(
                speaker: speaker
            )
            .frame(
                width: 340
            )
            .presentationCompactAdaptation(
                .popover
            )
        }
    }
}

// MARK: - Compact Dashboard

struct CompactSpeakerDashboard: View {

    @ObservedObject
    var speaker: SpeakerSystem

    var body: some View {

        VStack(
            alignment: .leading,
            spacing: 16
        ) {

            HStack {

                Label(
                    "Speaker",
                    systemImage:
                        speaker.activeRoute?
                            .type.icon
                        ?? "speaker.wave.2"
                )
                .font(.headline)

                Spacer()

                if speaker.audioSessionActive {

                    Circle()
                        .fill(.green)
                        .frame(
                            width: 8,
                            height: 8
                        )
                }
            }

            if let route =
                speaker.activeRoute {

                Text(route.name)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }

            Divider()

            HStack {

                Image(
                    systemName:
                        "speaker.wave.1"
                )

                Text(
                    "\(Int(speaker.systemVolume * 100))%"
                )
                .monospacedDigit()

                Spacer()

                Button {

                    speaker.toggleMute()

                } label: {

                    Image(
                        systemName:
                            speaker.isMuted
                            ? "speaker.wave.2"
                            : "speaker.slash"
                    )
                }
                .buttonStyle(.bordered)
            }

            Divider()

            Picker(
                "Mode",
                selection:
                    Binding(
                        get: {
                            speaker.configuration.mode
                        },
                        set: {
                            speaker.setMode($0)
                        }
                    )
            ) {

                ForEach(
                    SpeakerMode.allCases
                ) { mode in

                    Text(mode.title)
                        .tag(mode)
                }

            }
            .pickerStyle(.menu)

            Button {

                speaker.playTestTone()

            } label: {

                Label(
                    speaker.isPlayingTestTone
                    ? "Stop Test"
                    : "Test Speaker",
                    systemImage:
                        speaker.isPlayingTestTone
                        ? "stop.fill"
                        : "waveform"
                )
                .frame(
                    maxWidth: .infinity
                )
            }
            .buttonStyle(.borderedProminent)
        }
        .padding()
    }
}

// MARK: - Example App

struct SpeakerSystemDemo: View {

    var body: some View {

        SpeakerDashboard()
    }
}

#Preview {

    SpeakerDashboard()
}
```


